name: "Rails Specs CI"
on:
  push:
    branches: [ main, Run-test-automatically-on-Github ]
  pull_request:
    branches: [ main ]
jobs:
  rspec-test:
    name: RSpec
    runs-on: ubuntu-20.04
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@8f312efe1262fb463d906e9bf040319394c18d3e # v1.92
        with:
          bundler-cache: true
      # Add or replace database setup steps here
      # - name: Set up database schema
      #   run: bin/rails db:schema:load
      # Add or replace test runners here
      - name: Run tests
        run: bundler exec rspec spec/*
      - name: Uplaod coverage results
        uses: actions/upload-artifact@main
        if: always()
        with:
          name: coverage-report
          path: coverage
